version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  environment:
    RUBY_VERSION: 3.0.3
    NODE_VERSION: 16
    BUNDLER_VERSION: 2.2.32
    PROJECT_NAME: fleetyards

aliases:
  - &docker_login
      run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  - &setup_thor
      run: |
        sudo apt-get install ruby
        gem install thor

jobs:
  ci-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - *setup_thor
      - run: thor docker:build ci -p

  e2e-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - *setup_thor
      - run: thor docker:build ci e2e -p

  health-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - *setup_thor
      - run: thor docker:build health health latest -p

workflows:
  version: 2
  main:
    jobs:
      - ci-image
      - e2e-image
      - health-image
