version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  environment:
    RUBY_VERSION: 3.0.3
    NODE_VERSION: 14
    BUNDLER_VERSION: 2.2.32
    PROJECT_NAME: fleetyards

aliases:
  - &docker_login
      run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

jobs:
  ci-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd ci
          docker build -t $PROJECT_NAME/ci:$RUBY_VERSION --build-arg RUBY_VERSION --build-arg NODE_VERSION --build-arg BUNDLER_VERSION --build-arg NPM_VERSION .
      - run: docker push $PROJECT_NAME/ci:$RUBY_VERSION

  e2e-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd ci
          docker build -t $PROJECT_NAME/e2e:$RUBY_VERSION --build-arg RUBY_VERSION --build-arg NODE_VERSION --build-arg BUNDLER_VERSION --build-arg NPM_VERSION .
      - run: docker push $PROJECT_NAME/e2e:$RUBY_VERSION

  health-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd health
          docker build -t $PROJECT_NAME/health:latest .
      - run: docker push $PROJECT_NAME/health:latest

workflows:
  version: 2
  main:
    jobs:
      - ci-image
      - e2e-image
      - health-image
