version: 2.1

environmentDefaults: &environmentDefaults
  RUBY_VERSION: 2.7.1
  BUNDLER_VERSION: 2.1.4
  YARN_VERSION: 1.22.5
  PROJECT_NAME: fleetyards

defaults: &defaults
  docker:
    - image: cimg/base:2020.01

defaultSteps: &defaultSteps
  - setup_remote_docker
  - checkout
  - run: |
      echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

jobs:
  base-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_NAME: base
    steps:
      <<: *defaultSteps
      - run: |
          export IMAGE_TAG=$RUBY_VERSION
      - run: |
          cd ./$IMAGE_NAME
          docker build -t $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG

  ci-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_NAME: ci
    steps:
      <<: *defaultSteps
      - run: |
          export IMAGE_TAG=$RUBY_VERSION
      - run: |
          cd ./$IMAGE_NAME
          docker build -t $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG

  health-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_TAG: latest
      IMAGE_NAME: health
    steps:
      <<: *defaultSteps
      - run: |
          cd ./$IMAGE_NAME
          docker build -t $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  main:
    jobs:
      - base-image
      - ci-image:
          requires:
            - base-image
      - health-image
