version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  environment:
    RUBY_VERSION: 2.7.1
    BUNDLER_VERSION: 2.1.4
    PROJECT_NAME: fleetyards

aliases:
  - &docker_login
      run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

jobs:
  base-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd base
          docker build -t $PROJECT_NAME/base:$RUBY_VERSION --build-arg RUBY_VERSION --build-arg BUNDLER_VERSION --build-arg YARN_VERSION .
      - run: docker push $PROJECT_NAME/base:$RUBY_VERSION

  ci-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd ci
          docker build -t $PROJECT_NAME/ci:$RUBY_VERSION --build-arg RUBY_VERSION .
      - run: docker push $PROJECT_NAME/ci:$RUBY_VERSION

  health-image:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - *docker_login
      - run: |
          cd health
          docker build -t $PROJECT_NAME/health:latest .
      - run: docker push $PROJECT_NAME/health:latest

workflows:
  version: 2
  main:
    jobs:
      - base-image
      - ci-image:
          requires:
            - base-image
      - health-image
