version: 2.1

environmentDefaults: &environmentDefaults
  RUBY_VERSION: 2.7.1
  BUNDLER_VERSION: 2.1.4
  YARN_VERSION: 1.22.5
  IMAGE: fleetyards/$IMAGE_NAME:$IMAGE_TAG

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  steps:
    - setup_remote_docker
    - checkout
    - run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    - run: |
        cd ./$IMAGE_NAME
        docker build -t $IMAGE .
    - run: docker push $IMAGE

jobs:
  base-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_TAG: $RUBY_VERSION
      IMAGE_NAME: base

  ci-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_TAG: $RUBY_VERSION
      IMAGE_NAME: ci

  health-image:
    <<: *defaults
    environment:
      <<: *environmentDefaults
      IMAGE_TAG: latest
      IMAGE_NAME: health

workflows:
  version: 2
  main:
    jobs:
      - base-image
      - ci-image:
          requires:
            - base-image
      - health-image
